settings:
  enableDebugMode: false
  enablePermissions: true
warps:
  enable: true
  maxWarpsPerPlayer: 5
homes:
  enable: true
  maxHomesPerPlayer: 5
backpack:
  enable: true
  size: 27
tpa:
  enable: true
messages:
  general:
    Prefix: "§8[§9MPSA§8] §7"
    noPermission: "§cDu hast keine Rechte dafür."
    onlyByPlayer: "§cDieser Befehl kann nur von einem Spieler ausgeführt werden."
    addonDisabled: "§cDieses Addon wurde deaktiviert."
  homes:
    yourHomes: "§7Das sind deine Homes:"
    toManyHomes: "§7Du kannst keine weiteren Homes anlegen."
    homeAlreadyExists: "§7Dieser Home Existiert schon."
    homeAreDisabled: "§7Homes sind deaktiviert."
    homeNotExists: "§7Dieser Home Existiert nicht."
    teleportToHome: "§7Du hast dich Teleportiert."
    newHomeCreated: "§7Du hast dir ein neuen Home erstellt"
  warps:
    warps: "§7Das sind alle Warps:"
    toManyWarps: "§7Du kannst keine weiteren Warps anlegen."
    warpAlreadyExists: "§7Dieser Warp Existiert schon."
    warpsAreDisabled: "§7Warps sind deaktiviert."
    warpNotExists: "§7Dieser Warp Existiert nicht."
    teleportToWarp: "§7Du hast dich Teleportiert."
    newWarpCreated: "§7Du hast dir ein neuen Warp erstellt"
  tpa:
    playerNotFound: "§7Spieler nicht gefunden."
    cantTpToYourself: "§7Du kannst dich nicht zu dir selbst teleportieren."
    tpaRequest: "§7%player% möchte sich zu dir teleportieren. "
    tpaRequestAccept: "§7[§aAkzeptieren§7]"
    sendRequest: "§7Anfrage an %player% gesendet."
    noOpenRequests: "§7Es gibt keine ausstehende TPA-Anfrage."
    playerNotOnline: "Der Spieler, der die Anfrage gesendet hat, ist nicht mehr online."
    teleportTarget: "Du wurdest zu %player% teleportiert."
    teleportCommandUser: "Du hast die Teleportanfrage von %player% angenommen."
